export const OPTIONS = [
    'Kingdom Hearts moment',
    'Chat member says something sus',
    'Visit from Cosy sibling',
    'Alfie appears',
    'Caits laughs at her own joke',
    'Someone gets !frisky with Mayor Lewis',
    'RAID!!! HYPE',
    'Caits takes an L',
    'Certified Gamer Moment',
    'Otter time',
    'Someone calls Caits "Welsh" or "Irish"',
    'Caits thirsts over an NPC',
    'Caits thirsts over a chat member',
    'Bi panic',
    'Game gets reset',
    'Caits says something sus as a legit mistake',
    'Simp in chat',
    'Moss gets bullied',
    'Lina times someone out',
    'Glow is summoned by a puzzle',
    'Caits gets the big word in WoS',
    'Ice eatin time',
    'Jamie is chatting from work',
    'Korok goes goblin mode',
    'Flower of Scotland',
    'Tech issues',
    'Coffee break',
    'Nicky is wholesome but can\'t stay long',
    'Moss does something cringe',
    'Lina says something extra Swedish',
    'Caits "suggests" that you give her money',
    'Caits uses Scottish slang nobody gets',
    'Shrek rave',
    'Caits uses !PokeCatch',
    'Caits pics up her mic to get real',
    'Clap clap clap',
    'Limmy reference',
    'Shrek Rave'
]